---
- hosts: localhost
  tasks:
    - name: install packages (apt)
      become: yes
      with_items:
        - apache2
        - redis-server
        - libapache2-mod-wsgi
      apt:
        update_cache: yes
        name: "{{ item }}"

    - name: install packages (pip)
      become: yes
      with_items:
        - celery
        - Flask
        - Flask-HTTPAuth
        - Flask-RESTful
        - flask-restful-swagger
        - flower
        - redis
      pip:
        name: "{{ item }}"



    - name: Make sure target dir exists
      with_items:
        - /opt/flansible
        - /var/www/flansible
      become: yes
      file:
        path: "{{ item }}"
        state: directory

    - name: create flansible user
      become: yes
      user: 
        name: flansible

    - name: set acls
      become: yes
      acl: 
        name: /opt/flansible
        entity: flansible
        etype: user
        permissions: "rw"
        state: present

    - name: Clone Flansible
      become: yes
      git: 
        repo: https://github.com/trondhindenes/flansible.git
        dest: /opt/flansible

    - name: Configure wsgi file
      become: yes
      template:
        src: app.wsgi
        dest: /opt/flansible/Flansible/app.wsgi

    - name: enable wsgi in apache2
      become: yes
      apache2_module:
        state: present
        name: wsgi
      notify:
        - restart apache

    - name: make wsgi executable
      become: yes
      acl:
        name: /opt/flansible/Flansible/app.wsgi
        entity: flansible
        etype: user
        permissions: "rwx"
      notify:
        - restart apache

    - name: Configure apache app file
      become: yes
      template:
        src: site.xml
        dest: /etc/apache2/sites-available/flansible.conf
      notify:
        - restart apache

  handlers:
    - name: restart apache
      become: yes
      service:
        name: apache2
        state: restarted

